class_name PlayerWeaponPresentation
extends Node2D
## Presentation-only HD steel weapon layer for issue #168. It mirrors the
## existing PlayerVisual facing/action state instead of owning movement, the
## melee hitbox, damage, cooldown/timing, input, or collision. The authored
## steel sword (assets/sprites/player/hd/player_weapon.png, generated by
## assets/sprites/generate_player_weapon.py) is anchored at the wanderer's hand
## and rotated to face and sweep truthfully for all four directions.
##
## The held guard silhouette (idle/move/dash/relic) and the melee arc are two
## procedural poses of the same authored blade, so the weapon never relies on a
## single static front-facing image. A brief edge flash sharpens contact
## readability. This node adds no gameplay calls; the existing slash trail still
## spawns from the shared CombatFxSpawner, and the blade sweeps through it so the
## melee reads as one integrated effect rather than duplicated FX.

const WEAPON_TEXTURE: Texture2D = preload("res://assets/sprites/player/hd/player_weapon.png")
const HD_TEXTURE_FILTER: CanvasItem.TextureFilter = CanvasItem.TEXTURE_FILTER_LINEAR

## Authored geometry (cell pixels), mirrored from generate_player_weapon.py so
## the runtime pivots exactly on the hand and scales the blade by its true reach.
const GRIP_PIVOT: Vector2 = Vector2(40.0, 64.0)
const ART_PIVOT_TO_TIP_PX: float = 210.0
## On-screen grip→tip length at the shipped 2× camera. Sized so the hand-anchored
## blade tip stays inside the 24×24 melee hitbox envelope (far edge ≈26 px from
## the player) at full forward extension, reading as a wieldable arming sword
## against the ~42 px HD body without overstating the melee reach.
const DISPLAY_LENGTH_PX: float = 22.0

## Hand anchor = facing forward * FORWARD_HAND_PX + a small downward drop, so the
## sword sits at the wanderer's leading hand rather than the body center.
const FORWARD_HAND_PX: float = 4.0
const HAND_DROP_PX: float = 3.0

## Blade rotations are expressed relative to the facing forward angle, which keeps
## the guard and the slash truthful for every direction. Screen space is y-down,
## so positive relative angles cant the point toward the ground.
const REST_ROTATION_REL: float = 0.52
const WINDUP_ROTATION_REL: float = -1.45
const FOLLOW_ROTATION_REL: float = 1.45
## Presentation-only swing length; independent of the gameplay swing/cooldown.
const SWING_DURATION: float = 0.2

const IDLE_SWAY_DEGREES: float = 4.0
const IDLE_SWAY_FREQUENCY: float = 2.6
const MOVE_BOB_PX: float = 1.0
const MOVE_BOB_FREQUENCY: float = 11.0
const DASH_TUCK_REL: float = 0.9

const EDGE_FLASH_COLOR: Color = Color(0.7, 0.97, 1.0, 1.0)

@export var visual_path: NodePath

var _legacy_visual: PlayerVisual
var _blade: Sprite2D
var _animation_state: StringName = PlayerVisual.IDLE_ANIMATION
var _swing_elapsed: float = SWING_DURATION
var _elapsed: float = 0.0


func _ready() -> void:
	_ensure_blade()
	_legacy_visual = get_node_or_null(visual_path) as PlayerVisual
	if _legacy_visual == null:
		push_error("PlayerWeaponPresentation requires a PlayerVisual driver.")
		set_process(false)
		return
	_legacy_visual.animation_state_changed.connect(_on_animation_state_changed)
	_animation_state = _legacy_visual.animation_name


func _process(delta: float) -> void:
	if _legacy_visual == null:
		return
	_elapsed += delta
	_swing_elapsed = minf(_swing_elapsed + delta, SWING_DURATION)
	_apply_pose()


func get_blade_sprite() -> Sprite2D:
	_ensure_blade()
	return _blade


## Grip→tip length in world pixels for the current display scale; tests assert
## the blade never overstates the melee hitbox reach.
func base_scale() -> float:
	return DISPLAY_LENGTH_PX / ART_PIVOT_TO_TIP_PX


func _ensure_blade() -> void:
	if _blade != null:
		return
	_blade = Sprite2D.new()
	_blade.name = "HdWeapon"
	_blade.texture = WEAPON_TEXTURE
	_blade.texture_filter = HD_TEXTURE_FILTER
	# Anchor the drawn texture on the authored grip so rotation pivots on the hand.
	_blade.centered = false
	_blade.offset = -GRIP_PIVOT
	_blade.scale = Vector2.ONE * base_scale()
	add_child(_blade)


func _on_animation_state_changed(next_state: StringName) -> void:
	# Restart the presentation swing whenever the shared state driver re-enters
	# melee; the arc then tracks the same event that positions the melee hitbox.
	if next_state == PlayerVisual.MELEE_ANIMATION and _animation_state != PlayerVisual.MELEE_ANIMATION:
		_swing_elapsed = 0.0
	_animation_state = next_state


func _apply_pose() -> void:
	var facing: Vector2 = _facing_vector()
	var forward_angle: float = facing.angle()

	# Death drops the weapon; a hidden blade reads as defeated without touching
	# the health lifecycle that CombatFeedback/PlayerVisual already own.
	if _animation_state == PlayerVisual.DEATH_ANIMATION:
		_blade.visible = false
		return
	_blade.visible = true

	_blade.position = facing * FORWARD_HAND_PX + Vector2(0.0, HAND_DROP_PX)
	_blade.scale = Vector2.ONE * base_scale()
	_blade.rotation = forward_angle + _pose_rotation_rel()
	# Facing north tucks the sword behind the body; every other facing renders it
	# in front. z_index stays local so world/HUD layering is unaffected.
	_blade.z_index = -1 if _legacy_visual.facing_label == &"north" else 1
	_blade.self_modulate = _blade_modulate() * _legacy_visual.self_modulate


## Blade rotation relative to the facing forward direction for the current state.
func _pose_rotation_rel() -> float:
	match _animation_state:
		PlayerVisual.MELEE_ANIMATION:
			var progress: float = clampf(_swing_elapsed / SWING_DURATION, 0.0, 1.0)
			var eased: float = ease(progress, 2.2)
			return lerpf(WINDUP_ROTATION_REL, FOLLOW_ROTATION_REL, eased)
		PlayerVisual.DASH_ANIMATION:
			# Tuck the blade back along the dash so it trails instead of leading.
			return DASH_TUCK_REL
		PlayerVisual.MOVE_ANIMATION:
			return REST_ROTATION_REL
		_:
			# Idle/relic/hurt: lowered guard with a subtle living sway.
			return REST_ROTATION_REL + sin(_elapsed * IDLE_SWAY_FREQUENCY) * deg_to_rad(IDLE_SWAY_DEGREES)


func _blade_modulate() -> Color:
	if _animation_state != PlayerVisual.MELEE_ANIMATION:
		return Color.WHITE
	# Brighten the steel through the middle of the arc so contact reads cleanly.
	var progress: float = clampf(_swing_elapsed / SWING_DURATION, 0.0, 1.0)
	var flash: float = 1.0 - absf(progress - 0.5) / 0.5
	return Color.WHITE.lerp(EDGE_FLASH_COLOR, maxf(flash, 0.0))


func _facing_vector() -> Vector2:
	match _legacy_visual.facing_label:
		&"north":
			return Vector2.UP
		&"east":
			return Vector2.RIGHT
		&"west":
			return Vector2.LEFT
		_:
			return Vector2.DOWN
