#!/usr/bin/env python3
"""Deterministic builder for the hand-authored issue #95 pixel art.

Every frame and tile below is authored as an explicit per-pixel character
map (plus the standard pixel-artist derivations: mirror, 90-degree rotation,
one-pixel bounce shifts, and palette keying for telegraph/death states).
Colors come exclusively from docs/visual_bible.md ramps and signal colors.
Re-running the script reproduces the committed PNGs byte-for-byte:

  python3 assets/sprites/generate_authored_pixel_art.py

Outputs:
  assets/sprites/enemies/melee_chaser.png        (192x320 sheet, 43 frames)
  assets/sprites/enemies/melee_chaser_frames.tres (SpriteFrames over the sheet)
  assets/sprites/world/zone1_forest_tiles.png    (128x80 atlas of 16x16 tiles)
"""
from __future__ import annotations

import os

from PIL import Image

ROOT = os.path.dirname(os.path.abspath(__file__))

# --- Visual bible palette (docs/visual_bible.md section 2) -------------------
CANOPY = [(0x10, 0x0D, 0x16, 255), (0x1C, 0x18, 0x26, 255), (0x2A, 0x24, 0x38, 255)]
SOIL = [(0x2E, 0x21, 0x1B, 255), (0x4A, 0x36, 0x28, 255), (0x6B, 0x4E, 0x33, 255), (0x8F, 0x6D, 0x46, 255)]
MOSS = [(0x1E, 0x2B, 0x1D, 255), (0x33, 0x47, 0x2A, 255), (0x4F, 0x6B, 0x38, 255), (0x7A, 0x93, 0x4F, 255)]
STONE = [(0x2B, 0x2B, 0x33, 255), (0x45, 0x45, 0x4F, 255), (0x63, 0x63, 0x6E, 255)]
MAGENTA = [(0x5C, 0x1E, 0x52, 255), (0x9E, 0x29, 0x66, 255), (0xF2, 0x59, 0xB8, 255), (0xFF, 0xC8, 0xEC, 255)]
VIOLET = [(0x3A, 0x14, 0x45, 255), (0x94, 0x40, 0xAD, 255), (0xD9, 0x8F, 0xF0, 255)]
WIND_UP = (0xFF, 0xC7, 0x2E, 255)
ATTACK = (0xFF, 0x33, 0x40, 255)
DEATH = (0x38, 0x38, 0x42, 255)
SHADOW = (0x10, 0x0D, 0x16, 102)  # canopy-darkest contact shadow at ~40%

CHASER_PALETTE = {
    ".": None,
    "d": VIOLET[0],  # darkest ramp value doubles as the selective outline
    "m": VIOLET[1],
    "l": VIOLET[2],
    "Y": WIND_UP,
    "R": ATTACK,
    "D": DEATH,
    "c": CANOPY[2],  # cooled shading inside the death heap
    "s": SHADOW,
}

TILE_PALETTE = {
    ".": None,
    "0": CANOPY[0],
    "1": CANOPY[1],
    "2": CANOPY[2],
    "a": SOIL[0],
    "b": SOIL[1],
    "c": SOIL[2],
    "e": SOIL[3],
    "f": MOSS[0],
    "g": MOSS[1],
    "h": MOSS[2],
    "i": MOSS[3],
    "j": STONE[0],
    "k": STONE[1],
    "n": STONE[2],
    "p": MAGENTA[0],
    "q": MAGENTA[1],
    "r": MAGENTA[2],
    "t": MAGENTA[3],
}


def parse(text: str) -> list[str]:
    rows = [line for line in text.strip("\n").split("\n")]
    width = len(rows[0])
    for row in rows:
        assert len(row) == width, f"ragged row: {row!r} ({len(row)} != {width})"
    return rows


def hflip(rows: list[str]) -> list[str]:
    return [row[::-1] for row in rows]


def vflip(rows: list[str]) -> list[str]:
    return rows[::-1]


def rot90(rows: list[str]) -> list[str]:
    # Clockwise quarter turn; legal for tiles/FX per bible section 5.
    return ["".join(rows[len(rows) - 1 - x][y] for x in range(len(rows))) for y in range(len(rows[0]))]


def shift_up(rows: list[str], amount: int = 1) -> list[str]:
    blank = "." * len(rows[0])
    return rows[amount:] + [blank] * amount


def shift_down(rows: list[str], amount: int = 1) -> list[str]:
    blank = "." * len(rows[0])
    return [blank] * amount + rows[:-amount]


def remap(rows: list[str], table: dict[str, str]) -> list[str]:
    return ["".join(table.get(ch, ch) for ch in row) for row in rows]


def overlay(base: list[str], top: list[str]) -> list[str]:
    return [
        "".join(t if t != "." else b for b, t in zip(base_row, top_row))
        for base_row, top_row in zip(base, top)
    ]


def blit(image: Image.Image, rows: list[str], palette: dict[str, tuple], x0: int, y0: int) -> None:
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            color = palette[ch]
            if color is not None:
                image.putpixel((x0 + x, y0 + y), color)


# =============================================================================
# Melee chaser — 24x24 frames, violet ramp (bible section 2.3)
# A hunched, horned relic-hound: wide carapace, four claws, glowing pale eyes.
# Down/up bodies are symmetric so mirrored maps give the opposite step.
# =============================================================================

CHASER_DOWN_IDLE_A = parse("""
........................
........................
........................
.....dd........dd.......
.....ddd......ddd.......
......dmd....dmd........
......dmmddddmmd........
.....ddmmmmmmmmdd.......
....ddmmmmmmmmmmdd......
....dmmlmmmmmmlmmd......
...ddmllmmmmmmllmdd.....
...dmmllmmmmmmllmmd.....
...dmmmmmmmmmmmmmmd.....
...dmmmddmmmmddmmmd.....
...ddmmmmddddmmmmdd.....
....dmmmmmmmmmmmmd......
....ddmmdmmmmdmmdd......
.....dmddmmmmddmd.......
.....dd.dmdddmd.dd......
........ddd.ddd.........
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

CHASER_DOWN_IDLE_B = parse("""
........................
........................
........................
........................
.....dd........dd.......
.....ddd......ddd.......
......dmd....dmd........
......dmmddddmmd........
.....ddmmmmmmmmdd.......
....ddmlmmmmmmlmdd......
...ddmllmmmmmmllmdd.....
...dmmllmmmmmmllmmd.....
...dmmmmmmmmmmmmmmd.....
...dmmmddmmmmddmmmd.....
...ddmmmmddddmmmmdd.....
....dmmmmmmmmmmmmd......
....ddmmdmmmmdmmdd......
.....dmddmmmmddmd.......
.....dd.dmdddmd.dd......
........ddd.ddd.........
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

CHASER_DOWN_IDLE_C = parse("""
........................
........................
........................
........................
.....dd........dd.......
.....ddd......ddd.......
......dmd....dmd........
......dmmddddmmd........
.....ddmmmmmmmmdd.......
....ddmmmmmmmmmmdd......
...ddmdlmmmmmmdlmdd.....
...dmmdlmmmmmmdlmmd.....
...dmmmmmmmmmmmmmmd.....
...dmmmddmmmmddmmmd.....
...ddmmmmddddmmmmdd.....
....dmmmmmmmmmmmmd......
....ddmmdmmmmdmmdd......
.....dmddmmmmddmd.......
.....dd.dmdddmd.dd......
........ddd.ddd.........
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

# Walk, left legs forward ("L"); mirrored for the right step.
CHASER_DOWN_WALK_L = parse("""
........................
........................
........................
.....dd........dd.......
.....ddd......ddd.......
......dmd....dmd........
......dmmddddmmd........
.....ddmmmmmmmmdd.......
....ddmmmmmmmmmmdd......
....dmmlmmmmmmlmmd......
...ddmllmmmmmmllmdd.....
...dmmllmmmmmmllmmd.....
...dmmmmmmmmmmmmmmd.....
...dmmmddmmmmddmmmd.....
...ddmmmmddddmmmmdd.....
....dmmmmmmmmmmmmd......
...ddmmdmmmmmmdmmdd.....
...dmdddmmmmmmddmmd.....
...dd..dmdddddd.dmd.....
.......ddd....d.ddd.....
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

CHASER_DOWN_WALK_P = parse("""
........................
........................
........................
....dd........dd........
....ddd......ddd........
.....dmd....dmd.........
.....dmmddddmmd.........
....ddmmmmmmmmdd........
...ddmmmmmmmmmmdd.......
...dmmlmmmmmmlmmd.......
..ddmllmmmmmmllmdd......
..dmmllmmmmmmllmmd......
..dmmmmmmmmmmmmmmd......
..dmmmddmmmmddmmmd......
..ddmmmmddddmmmmdd......
...dmmmmmmmmmmmmd.......
...ddmmdmmmmdmmdd.......
....dmddmmmmddmd........
....dd.dmdddmd.dd.......
.......ddd.ddd..........
........................
.....ssssssssss.........
...ssssssssssssss.......
........................
""")

# Wind-up crouch: mass pulled back and low, horns flared. Keyed frames swap
# the violet highlights toward the #FFC72E telegraph color, brightest last.
CHASER_WINDUP_BASE = parse("""
........................
........................
........................
........................
........................
....dd..........dd......
....ddd........ddd......
.....dmd......dmd.......
.....dmmddddddmmd.......
....ddmmmmmmmmmmdd......
...ddmlmmmmmmmmlmdd.....
...dmmllmmmmmmllmmd.....
...dmmllmmmmmmllmmd.....
...dmmmmmmmmmmmmmmd.....
...dmmmddmmmmddmmmd.....
...ddmmmmddddmmmmdd.....
....dmmmmmmmmmmmmd......
...ddmmdmmmmmmdmmdd.....
...dmddmmmmmmmmddmd.....
...dd.dmddddddmd.dd.....
......ddd....ddd........
.....ssssssssssss.......
...ssssssssssssssss.....
........................
""")

# Attack lunge: frame 1 rears, frame 2 is the contact frame with extended
# claws and a short attack-red slash arc, frame 3 settles back.
CHASER_ATTACK_REAR = parse("""
........................
........................
.....dd........dd.......
.....ddd......ddd.......
......dmd....dmd........
......dmmddddmmd........
.....ddmmmmmmmmdd.......
....ddmmmmmmmmmmdd......
....dmmlmmmmmmlmmd......
...ddmllmmmmmmllmdd.....
...dmmllmmmmmmllmmd.....
...dmmmmmmmmmmmmmmd.....
...dmmmddmmmmddmmmd.....
...ddmmmmddddmmmmdd.....
....dmmmmmmmmmmmmd......
....ddmmdmmmmdmmdd......
.....dmddmmmmddmd.......
.....dd.dmdddmd.dd......
........ddd.ddd.........
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

CHASER_ATTACK_CONTACT = parse("""
........................
........................
........................
........................
.....dd........dd.......
......dd......dd........
......dmd....dmd........
......dmmddddmmd........
.....ddmmmmmmmmdd.......
....ddmlmmmmmmlmdd......
....dmmllmmmmllmmd......
....dmmmmmmmmmmmmd......
....dmmmddmmddmmmd......
...ddmmmmddddmmmmdd.....
...dmmdmmmmmmmmdmmd.....
...dmdlmmmmmmmmldmd.....
...ddddmmmmmmmmdddd.....
..R.dlddmmmmddld.R......
.RR.dd.dddddd.dd.RR.....
.R....R......R....R.....
......RR....RR..........
.....ssssssssssss.......
...ssssssssssssssss.....
........................
""")

# Hurt recoil: head snaps back, highlights flare bright.
CHASER_HURT_A = parse("""
........................
........................
........................
....dd..........dd......
....ddd........ddd......
.....dmd......dmd.......
.....dmmddddddmmd.......
....ddmmmmmmmmmmdd......
....dmlmmmmmmmmlmd......
...ddllmmmmmmmmlldd.....
...dmllmmmmmmmmllmd.....
...dmmmmmmmmmmmmmmd.....
...dmmmdddmmdddmmmd.....
...ddmmmmddddmmmmdd.....
....dmmmmmmmmmmmmd......
....ddmmdmmmmdmmdd......
.....dmddmmmmddmd.......
.....dd.dmdddmd.dd......
........ddd.ddd.........
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

# Death collapse keys: kneel, fall, heap; the heap is re-keyed into the
# death tint for the held final frame.
CHASER_DEATH_KNEEL = parse("""
........................
........................
........................
........................
........................
....dd..........dd......
....ddd........ddd......
.....dmd......dmd.......
.....dmmddddddmmd.......
....ddmmmmmmmmmmdd......
...ddmlmmmmmmmmlmdd.....
...dmmlmmmmmmmmlmmd.....
...dmmmmmmmmmmmmmmd.....
...dmmmddmmmmddmmmd.....
...ddmmmmddddmmmmdd.....
....dmmmmmmmmmmmmd......
....ddmdmmmmmmdmdd......
.....ddddmmmmdddd.......
.......dmddddmd.........
.......dd....dd.........
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

CHASER_DEATH_FALL = parse("""
........................
........................
........................
........................
........................
........................
........................
........................
.....dd........dd.......
.....ddd......ddd.......
......dmd....dmd........
.....ddmmddddmmdd.......
....ddmmmmmmmmmmdd......
...ddmlmmmmmmmmlmdd.....
...dmmlmmmmmmmmlmmd.....
...dmmmmmmmmmmmmmmd.....
...dmmmddmmmmddmmmd.....
...ddmmmmddddmmmmdd.....
....ddmmmmmmmmmmdd......
.....dddddddddddd.......
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

CHASER_DEATH_HEAP = parse("""
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
......dd......dd........
.....ddddddddddddd......
....ddmmmmmmmmmmmdd.....
...ddmmlmmmmmmlmmmdd....
...dmmmmmmmmmmmmmmmd....
...dmmddmmmmmmddmmmd....
...ddddddddddddddddd....
........................
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

# Up-facing (back view): no eyes or maw; armored back plates instead.
CHASER_UP_IDLE_A = parse("""
........................
........................
........................
.....dd........dd.......
.....ddd......ddd.......
......dmd....dmd........
......dmmddddmmd........
.....ddmmmmmmmmdd.......
....ddmmmlmmlmmmdd......
....dmmmlmmmmlmmmd......
...ddmmmlmmmmlmmmdd.....
...dmmmmmlmmlmmmmmd.....
...dmmmmmlmmlmmmmmd.....
...dmmmmmmllmmmmmmd.....
...ddmmmmmllmmmmmdd.....
....dmmmmmmmmmmmmd......
....ddmmdmmmmdmmdd......
.....dmddmmmmddmd.......
.....dd.dmdddmd.dd......
........ddd.ddd.........
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

CHASER_UP_IDLE_B = parse("""
........................
........................
........................
........................
.....dd........dd.......
.....ddd......ddd.......
......dmd....dmd........
......dmmddddmmd........
.....ddmmmmmmmmdd.......
....ddmmlmmmmlmmdd......
...ddmmmlmmmmlmmmdd.....
...dmmmmmlmmlmmmmmd.....
...dmmmmmlmmlmmmmmd.....
...dmmmmmmllmmmmmmd.....
...ddmmmmmllmmmmmdd.....
....dmmmmmmmmmmmmd......
....ddmmdmmmmdmmdd......
.....dmddmmmmddmd.......
.....dd.dmdddmd.dd......
........ddd.ddd.........
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

CHASER_UP_IDLE_C = parse("""
........................
........................
........................
........................
.....dd........dd.......
.....ddd......ddd.......
......dmd....dmd........
......dmmddddmmd........
.....ddmmmmmmmmdd.......
....ddmmmlmmlmmmdd......
...ddmmmdlmmldmmmdd.....
...dmmmmdlmmldmmmmd.....
...dmmmmmlmmlmmmmmd.....
...dmmmmmmllmmmmmmd.....
...ddmmmmmllmmmmmdd.....
....dmmmmmmmmmmmmd......
....ddmmdmmmmdmmdd......
.....dmddmmmmddmd.......
.....dd.dmdddmd.dd......
........ddd.ddd.........
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

CHASER_UP_WALK_L = parse("""
........................
........................
........................
.....dd........dd.......
.....ddd......ddd.......
......dmd....dmd........
......dmmddddmmd........
.....ddmmmmmmmmdd.......
....ddmmmlmmlmmmdd......
....dmmmlmmmmlmmmd......
...ddmmmlmmmmlmmmdd.....
...dmmmmmlmmlmmmmmd.....
...dmmmmmlmmlmmmmmd.....
...dmmmmmmllmmmmmmd.....
...ddmmmmmllmmmmmdd.....
....dmmmmmmmmmmmmd......
...ddmmdmmmmmmdmmdd.....
...dmdddmmmmmmddmmd.....
...dd..dmdddddd.dmd.....
.......ddd....d.ddd.....
........................
......ssssssssss........
....ssssssssssssss......
........................
""")

CHASER_UP_WALK_P = parse("""
........................
........................
........................
....dd........dd........
....ddd......ddd........
.....dmd....dmd.........
.....dmmddddmmd.........
....ddmmmmmmmmdd........
...ddmmmlmmlmmmdd.......
...dmmmlmmmmlmmmd.......
..ddmmmlmmmmlmmmdd......
..dmmmmmlmmlmmmmmd......
..dmmmmmlmmlmmmmmd......
..dmmmmmmllmmmmmmd......
..ddmmmmmllmmmmmdd......
...dmmmmmmmmmmmmd.......
...ddmmdmmmmdmmdd.......
....dmddmmmmddmd........
....dd.dmdddmd.dd.......
.......ddd.ddd..........
........................
.....ssssssssss.........
...ssssssssssssss.......
........................
""")

# Side view, facing right: head and horn lead right, tail trails left.
CHASER_SIDE_IDLE_A = parse("""
........................
........................
........................
........................
..............dd........
.............ddd........
...........ddmd.........
.........ddmmmddd.......
....ddddmmmmmmmmdd......
..dddmmmmmmmmmmmmdd.....
.ddmmmmmmmmmmmmmlmd.....
.dmmmmmmmmmmmmmmlld.....
..ddmmmmmmmmmmmmmmdd....
...dmmmmmmmmmmmmddd.....
...dmmdmmmmmdmmmd.......
...ddmdmmmmmdmmdd.......
....dmddmmmmddmd........
....dmd.dddd.dmd........
....ddd......ddd........
........................
........................
....ssssssssssss........
..ssssssssssssssss......
........................
""")

CHASER_SIDE_IDLE_B = parse("""
........................
........................
........................
........................
........................
..............dd........
.............ddd........
...........ddmd.........
.........ddmmmddd.......
....ddddmmmmmmmmdd......
..dddmmmmmmmmmmmlmd.....
.ddmmmmmmmmmmmmmlld.....
.dmmmmmmmmmmmmmmmmd.....
..ddmmmmmmmmmmmmddd.....
...dmmdmmmmmdmmmd.......
...ddmdmmmmmdmmdd.......
....dmddmmmmddmd........
....dmd.dddd.dmd........
....ddd......ddd........
........................
........................
....ssssssssssss........
..ssssssssssssssss......
........................
""")

CHASER_SIDE_IDLE_C = parse("""
........................
........................
........................
........................
........................
..............dd........
.............ddd........
...........ddmd.........
.........ddmmmddd.......
....ddddmmmmmmmmdd......
..dddmmmmmmmmmmmdmd.....
.ddmmmmmmmmmmmmmdld.....
.dmmmmmmmmmmmmmmmmd.....
..ddmmmmmmmmmmmmddd.....
...dmmdmmmmmdmmmd.......
...ddmdmmmmmdmmdd.......
....dmddmmmmddmd........
....dmd.dddd.dmd........
....ddd......ddd........
........................
........................
....ssssssssssss........
..ssssssssssssssss......
........................
""")

# Side walk, three authored leg poses: open stride, pass, opposite stride.
CHASER_SIDE_WALK_O = parse("""
........................
........................
........................
........................
..............dd........
.............ddd........
...........ddmd.........
.........ddmmmddd.......
....ddddmmmmmmmmdd......
..dddmmmmmmmmmmmmdd.....
.ddmmmmmmmmmmmmmlmd.....
.dmmmmmmmmmmmmmmlld.....
..ddmmmmmmmmmmmmmmdd....
...dmmmmmmmmmmmmddd.....
...dmdmmmmmmmdmmd.......
...ddmddmmmmmdmddd......
...dmd.dmmmmd.dmd.......
..dmd..ddddmd..dmd......
..ddd......dd..ddd......
........................
........................
....ssssssssssss........
..ssssssssssssssss......
........................
""")

CHASER_SIDE_WALK_P = parse("""
........................
........................
........................
........................
..............dd........
.............ddd........
...........ddmd.........
.........ddmmmddd.......
....ddddmmmmmmmmdd......
..dddmmmmmmmmmmmmdd.....
.ddmmmmmmmmmmmmmlmd.....
.dmmmmmmmmmmmmmmlld.....
..ddmmmmmmmmmmmmmmdd....
...dmmmmmmmmmmmmddd.....
...dmmdmmmmmmdmmd.......
...ddddmmmmmmdddd.......
.....dmddddddmd.........
.....dmd....dmd.........
.....ddd....ddd.........
........................
........................
....ssssssssssss........
..ssssssssssssssss......
........................
""")

CHASER_SIDE_WALK_O2 = parse("""
........................
........................
........................
........................
..............dd........
.............ddd........
...........ddmd.........
.........ddmmmddd.......
....ddddmmmmmmmmdd......
..dddmmmmmmmmmmmmdd.....
.ddmmmmmmmmmmmmmlmd.....
.dmmmmmmmmmmmmmmlld.....
..ddmmmmmmmmmmmmmmdd....
...dmmmmmmmmmmmmddd.....
...dmdmmmmmmmdmmd.......
..ddmddmmmmmddmddd......
..dmd..dmmmd..dmd.......
..dmd..dmddd...dmd......
..ddd..dd......ddd......
........................
........................
....ssssssssssss........
..ssssssssssssssss......
........................
""")


def keyed_windup(frame_index: int) -> list[str]:
    # Progressive telegraph keying: horn tips, then highlights, then the
    # carapace itself shift to the #FFC72E signal color.
    base = CHASER_WINDUP_BASE
    if frame_index == 0:
        return remap(base, {"l": "Y"})
    if frame_index == 1:
        rows = remap(base, {"l": "Y"})
        # Flood the upper carapace rows with the key color.
        keyed = []
        for y, row in enumerate(rows):
            if 9 <= y <= 12:
                row = row.replace("m", "Y")
            keyed.append(row)
        return keyed
    return remap(base, {"l": "Y", "m": "Y"})


def death_frames() -> list[list[str]]:
    heap_tinted = remap(CHASER_DEATH_HEAP, {"m": "D", "l": "D", "d": "c"})
    heap_mid = remap(CHASER_DEATH_HEAP, {"l": "m"})
    return [
        CHASER_HURT_A,
        CHASER_DEATH_KNEEL,
        CHASER_DEATH_FALL,
        heap_mid,
        heap_tinted,
    ]


def chaser_animations() -> dict[str, dict]:
    down_idle = [CHASER_DOWN_IDLE_A, CHASER_DOWN_IDLE_B, CHASER_DOWN_IDLE_C, CHASER_DOWN_IDLE_B]
    up_idle = [CHASER_UP_IDLE_A, CHASER_UP_IDLE_B, CHASER_UP_IDLE_C, CHASER_UP_IDLE_B]
    side_idle = [CHASER_SIDE_IDLE_A, CHASER_SIDE_IDLE_B, CHASER_SIDE_IDLE_C, CHASER_SIDE_IDLE_B]

    def six_step(step_left: list[str], passing: list[str]) -> list[list[str]]:
        step_right = hflip(step_left)
        return [
            step_left,
            shift_up(passing),
            step_right,
            step_right,
            shift_up(passing),
            step_left,
        ]

    down_walk = six_step(CHASER_DOWN_WALK_L, CHASER_DOWN_WALK_P)
    up_walk = six_step(CHASER_UP_WALK_L, CHASER_UP_WALK_P)
    side_walk = [
        CHASER_SIDE_WALK_O,
        shift_up(CHASER_SIDE_WALK_P),
        CHASER_SIDE_WALK_O2,
        shift_up(CHASER_SIDE_WALK_O2),
        shift_up(CHASER_SIDE_WALK_P),
        shift_up(CHASER_SIDE_WALK_O),
    ]

    return {
        "idle_down": {"frames": down_idle, "loop": True, "speed": 6.0},
        "idle_up": {"frames": up_idle, "loop": True, "speed": 6.0},
        "idle_side": {"frames": side_idle, "loop": True, "speed": 6.0},
        "walk_down": {"frames": down_walk, "loop": True, "speed": 10.0},
        "walk_up": {"frames": up_walk, "loop": True, "speed": 10.0},
        "walk_side": {"frames": side_walk, "loop": True, "speed": 10.0},
        "windup": {"frames": [keyed_windup(i) for i in range(3)], "loop": False, "speed": 8.0},
        "attack_melee": {
            "frames": [CHASER_ATTACK_REAR, CHASER_ATTACK_CONTACT, CHASER_WINDUP_BASE],
            "loop": False,
            "speed": 12.0,
        },
        "hurt": {"frames": [CHASER_HURT_A, remap(CHASER_HURT_A, {"m": "l"})], "loop": False, "speed": 12.0},
        "death": {"frames": death_frames(), "loop": False, "speed": 10.0},
    }


CHASER_LOGICAL_FRAME = 24
CHASER_FRAME = 32
CHASER_SHEET_COLUMNS = 6

ANIMATION_ROW_ORDER = [
    "idle_down",
    "idle_up",
    "idle_side",
    "walk_down",
    "walk_up",
    "walk_side",
    "windup",
    "attack_melee",
    "hurt",
    "death",
]


def build_chaser_sheet() -> tuple[Image.Image, dict[str, dict]]:
    animations = chaser_animations()
    sheet = Image.new(
        "RGBA",
        (CHASER_SHEET_COLUMNS * CHASER_FRAME, len(ANIMATION_ROW_ORDER) * CHASER_FRAME),
        (0, 0, 0, 0),
    )
    for row, name in enumerate(ANIMATION_ROW_ORDER):
        for column, frame in enumerate(animations[name]["frames"]):
            logical_frame = Image.new(
                "RGBA", (CHASER_LOGICAL_FRAME, CHASER_LOGICAL_FRAME), (0, 0, 0, 0)
            )
            blit(logical_frame, frame, CHASER_PALETTE, 0, 0)
            display_frame = logical_frame.resize(
                (CHASER_FRAME, CHASER_FRAME), Image.Resampling.NEAREST
            )
            sheet.alpha_composite(display_frame, (column * CHASER_FRAME, row * CHASER_FRAME))
    return sheet, animations


def write_sprite_frames_tres(path: str, animations: dict[str, dict]) -> None:
    subresources: list[str] = []
    animation_blocks: list[str] = []
    for row, name in enumerate(ANIMATION_ROW_ORDER):
        animation = animations[name]
        frame_entries: list[str] = []
        for column in range(len(animation["frames"])):
            atlas_id = f"AtlasTexture_{name}_{column}"
            subresources.append(
                f'[sub_resource type="AtlasTexture" id="{atlas_id}"]\n'
                f'atlas = ExtResource("1_sheet")\n'
                f"region = Rect2({column * CHASER_FRAME}, {row * CHASER_FRAME}, {CHASER_FRAME}, {CHASER_FRAME})\n"
            )
            frame_entries.append(
                '{\n"duration": 1.0,\n"texture": SubResource("%s")\n}' % atlas_id
            )
        loop = "true" if animation["loop"] else "false"
        animation_blocks.append(
            '{\n"frames": [%s],\n"loop": %s,\n"name": &"%s",\n"speed": %.1f\n}'
            % (", ".join(frame_entries), loop, name, animation["speed"])
        )
    load_steps = len(subresources) + 2
    content = (
        f'[gd_resource type="SpriteFrames" load_steps={load_steps} format=3]\n\n'
        '[ext_resource type="Texture2D" path="res://assets/sprites/enemies/melee_chaser.png" id="1_sheet"]\n\n'
        + "\n".join(subresources)
        + "\n[resource]\nanimations = ["
        + ", ".join(animation_blocks)
        + "]\n"
    )
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)


# =============================================================================
# Zone 1 forest tileset — 16x16 tiles in a 128x80 atlas (8 columns x 5 rows)
# Row 0: floor variants  Row 1: wall variants  Row 2: edges + outer corners
# Row 3: inner corners + static corruption veins  Row 4: two shimmer loops
# =============================================================================

FLOOR_MOSS_PLAIN = parse("""
gggghggggggflggg
gghhhgggggggggg.
gghgggggggggggg.
gggggggggggggggg
hggggggfggggggh.
ggggggffggggghh.
gggggggggghggggg
ggggggggghihgggg
gfggggggghhggggg
gffggggggggggggg
gggggggggggggggg
gggghggggggggggg
ggghhgggggggfggg
ggggggggggggffgg
gghggggggggggggg
gghhggggghgggggg
""".replace("l", "h").replace(".", "g"))

FLOOR_MOSS_TUFTS = parse("""
gggggggggghggggg
gghgggggghihgggg
ghihggggghhggggg
gghhgggggggggggg
gggggggggggggghg
ggggggggggggghih
ggggghgggggggghh
gggghihggggggggg
gggghhgggggfgggg
gggggggggggffggg
ghgggggggggggggg
hihggggggggggggg
ghhgggggghgggggg
gggggggghihggggg
ggggfgggghhggggg
ggggffgggggggggg
""")

FLOOR_SOIL_PATCH = parse("""
gggggggggggggggg
ggggggffbbfggggg
gggggfbbccbfgggg
ggggfbcccccbfggg
ggggfbccecccbggg
gggfbcceeeccbggg
gggfbccceeccbggg
ggggfbccccbbfggg
gggggfbbccbfgggg
ggggggffbbfggggg
gggggggggggggggg
gghggggggggggggg
ghihggggggghgggg
gghhgggggghhgggg
gggggggggggggggg
gggggfggggggggg.
""".replace(".", "g"))

FLOOR_ROOT = parse("""
gggggggggggggggg
ggggggggggggggg.
gghgggggggabbagg
ghihggggabbccbag
gghhgggabccbbbag
ggggggabcbbagggg
gggggabcbbaggggg
gggggabbbagggggg
ggggabbbaggggggg
ggggabbagggggggg
ggggabbagggghggg
gggggabbagghhhgg
ggggggabbagghggg
gggggggggggggggg
ggfgggggggggggg.
ggffggggggggggg.
""".replace(".", "g"))

# Wall variants — dark silhouettes, lowest saturation on screen. Canopy void,
# bark trunks, worked stone, root-hung canopy; mirrors give the 8 variants.
WALL_CANOPY_A = parse("""
1110011111001111
1100000110001111
1110011111000111
1111111111100011
0111211111111111
0011111111121111
1111110011111111
1111100011110011
1211110011100001
1111111111000011
1111001111111111
1100000111111211
1000001112111111
1100111111110111
1111111110000111
1110011111001111
""")

WALL_CANOPY_B = parse("""
1111100111111001
1111000011110000
1121100111111001
1111111111111111
1001111111001112
0001111210001111
1001111111001111
1111100111111111
1111000111111001
1112001111110001
1111111111111011
0011111100111111
0011121100111111
1111111111111121
1100111111011111
1110011111111111
""")

WALL_TRUNK = parse("""
11ab0110abb01111
11abb010abb01011
11aab010aab01111
110ab110abb01111
11abb010aab01121
11ab0010abb01111
11ab0110abb01111
11aab010ab001111
11abb012abb01111
11ab0010aab01011
110ab010abb01111
11abb110abb01111
11ab0010aab01111
11aab010abb01211
11abb010ab001111
11ab0110abb01111
""")

WALL_STONE = parse("""
nnnnnjnnnnnnkjnn
kkkkkjkkkkkkkjkk
kkjjkjkkkjjkkjkk
jjjjjjjjjjjjjjjj
nnkjnnnnnnjnnnnn
kkkjkkkkkkjkkkkk
kjkjkkjjkkjkkjjk
jjjjjjjjjjjjjjjj
nnnnnnkjnnnnnnjn
kkkkkkkjkkkkkkjk
kkjjkkkjkkkjjkjk
jjjjjjjjjjjjjjjj
nnjnnnnnnnkjnnnn
kkjkkkkkkkkjkkkk
kjjkkjjkkkkjkkjk
jjjjjjjjjjjjjjjj
""")

WALL_ROOTS = parse("""
1a11011110a11011
1ab1101111ab1111
11a1111011a11101
11ab11011ab11111
111a11111a111011
111ab1111ab11111
1111a11111a11111
1111111111b11101
1011121111111111
1111111100111111
1100111111111211
1111111111100111
1211110011111111
1111100111111011
1100111111100111
1111011111001111
""")

# Edge rims: transparent overlays laid over the canopy base on wall cells
# that touch floor. Authored for floor-to-the-north; rotations cover the rest.
RIM_N = parse("""
hihhhhihhhhihhhh
ghgghhgg.ghhg.hg
.g...g.....g....
................
................
................
................
................
................
................
................
................
................
................
................
................
""")

RIM_INNER_NE = parse("""
............hihh
..............hg
...............g
................
................
................
................
................
................
................
................
................
................
................
................
................
""")

# Corruption veins — relic-magenta intrusions with straight seams and 1px
# glitch jogs (bible section 4). Transparent overlays for the vein layer.
VEIN_DIAGONAL = parse("""
................
..............p.
.............qr.
............qq.p
...........rq...
..........qr....
.....p...qq.....
....pq..qr......
.....qrqq.......
......rq........
.....qr.........
....qq...p......
...rq...........
..qr............
..q.............
.p..............
""")

VEIN_BRANCH = parse("""
.p.........p....
.q..........q...
..rq........qr..
...qq......qq...
....qr....rq....
.....qq..qq.....
......qrqq......
.......rq.......
.......qr.......
.......qq.......
........qr......
........qq......
.......p.qr.....
..........qq....
...........qr...
............q...
""")

# Ordered path along VEIN_DIAGONAL's core, bottom-left to top-right; shimmer
# loop A runs a bright pulse window along it, one quarter per frame.
VEIN_DIAGONAL_PATH = [
    (1, 15), (2, 14), (2, 13), (3, 12), (4, 11), (4, 10) if False else (5, 10),
    (4, 11), (5, 10), (6, 9), (7, 8), (8, 8), (9, 7), (8, 7), (10, 6), (9, 6),
    (10, 5), (11, 4), (12, 3), (12, 2), (13, 2), (13, 1), (14, 1),
]


def _pulse_frame(base: list[str], path: list[tuple[int, int]], window_index: int) -> list[str]:
    grid = [list(row) for row in base]
    quarter = max(len(path) // 4, 1)
    start = window_index * quarter
    lit = path[start:start + quarter + 2]
    for x, y in lit:
        if grid[y][x] in ("q", "r", "p"):
            grid[y][x] = "t"
    return ["".join(row) for row in grid]


def shimmer_loop_a() -> list[list[str]]:
    return [_pulse_frame(VEIN_DIAGONAL, VEIN_DIAGONAL_PATH, i) for i in range(4)]


def shimmer_loop_b() -> list[list[str]]:
    # Whole-vein breathing pulse: dim, mid, bright, mid.
    dim = remap(VEIN_BRANCH, {"r": "q", "q": "p"})
    mid = VEIN_BRANCH
    bright = remap(VEIN_BRANCH, {"q": "r", "r": "t"})
    return [dim, mid, bright, mid]


TILE = 16
ATLAS_COLUMNS = 8
ATLAS_ROWS = 5


def zone1_tiles() -> dict[tuple[int, int], list[str]]:
    edge_base = WALL_CANOPY_A

    def edge(rim: list[str]) -> list[str]:
        return overlay(edge_base, rim)

    rim_n = RIM_N
    rim_e = rot90(rim_n)
    rim_s = rot90(rim_e)
    rim_w = rot90(rim_s)
    inner_ne = RIM_INNER_NE
    inner_se = rot90(inner_ne)
    inner_sw = rot90(inner_se)
    inner_nw = rot90(inner_sw)

    tiles: dict[tuple[int, int], list[str]] = {}
    # Row 0 — floor variants (6).
    floors = [
        FLOOR_MOSS_PLAIN,
        FLOOR_MOSS_TUFTS,
        FLOOR_SOIL_PATCH,
        FLOOR_ROOT,
        hflip(FLOOR_MOSS_TUFTS),
        vflip(FLOOR_SOIL_PATCH),
    ]
    for index, rows in enumerate(floors):
        tiles[(index, 0)] = rows
    # Row 1 — wall variants (8).
    walls = [
        WALL_CANOPY_A,
        WALL_CANOPY_B,
        WALL_TRUNK,
        WALL_STONE,
        WALL_ROOTS,
        hflip(WALL_TRUNK),
        hflip(WALL_STONE),
        hflip(WALL_ROOTS),
    ]
    for index, rows in enumerate(walls):
        tiles[(index, 1)] = rows
    # Row 2 — edges (4) + outer corners (4): rims toward the adjacent floor.
    tiles[(0, 2)] = edge(rim_n)
    tiles[(1, 2)] = edge(rim_e)
    tiles[(2, 2)] = edge(rim_s)
    tiles[(3, 2)] = edge(rim_w)
    tiles[(4, 2)] = edge(overlay(rim_n, rim_e))  # floor N+E
    tiles[(5, 2)] = edge(overlay(rim_s, rim_e))  # floor S+E
    tiles[(6, 2)] = edge(overlay(rim_s, rim_w))  # floor S+W
    tiles[(7, 2)] = edge(overlay(rim_n, rim_w))  # floor N+W
    # Row 3 — inner corners (4) + static corruption veins (4).
    tiles[(0, 3)] = edge(inner_ne)
    tiles[(1, 3)] = edge(inner_se)
    tiles[(2, 3)] = edge(inner_sw)
    tiles[(3, 3)] = edge(inner_nw)
    tiles[(4, 3)] = VEIN_DIAGONAL
    tiles[(5, 3)] = VEIN_BRANCH
    tiles[(6, 3)] = rot90(VEIN_DIAGONAL)
    tiles[(7, 3)] = hflip(VEIN_BRANCH)
    # Row 4 — two 4-frame shimmer loops.
    for index, rows in enumerate(shimmer_loop_a()):
        tiles[(index, 4)] = rows
    for index, rows in enumerate(shimmer_loop_b()):
        tiles[(4 + index, 4)] = rows
    return tiles


def build_zone1_atlas() -> Image.Image:
    atlas = Image.new("RGBA", (ATLAS_COLUMNS * TILE, ATLAS_ROWS * TILE), (0, 0, 0, 0))
    for (column, row), rows in zone1_tiles().items():
        blit(atlas, rows, TILE_PALETTE, column * TILE, row * TILE)
    return atlas


def main() -> None:
    sheet, animations = build_chaser_sheet()
    enemies_dir = os.path.join(ROOT, "enemies")
    os.makedirs(enemies_dir, exist_ok=True)
    sheet.save(os.path.join(enemies_dir, "melee_chaser.png"), optimize=True)
    write_sprite_frames_tres(os.path.join(enemies_dir, "melee_chaser_frames.tres"), animations)
    print("wrote melee_chaser.png", sheet.size)

    atlas = build_zone1_atlas()
    world_dir = os.path.join(ROOT, "world")
    os.makedirs(world_dir, exist_ok=True)
    atlas.save(os.path.join(world_dir, "zone1_forest_tiles.png"), optimize=True)
    print("wrote zone1_forest_tiles.png", atlas.size)


if __name__ == "__main__":
    main()
